# Generated by Django 2.1 on 2019-04-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('to_par', models.IntegerField()),
                ('golf_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_course', to='web.GolfCourse')),
            ],
        ),
    ]
