# Generated by Django 2.1 on 2019-04-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190414_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
