# Generated by Django 2.1 on 2019-04-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='user_golf_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_golf_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='user_score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='golf_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='golf_course', to='web.GolfCourse'),
        ),
    ]
