# Generated by Django 2.1 on 2019-04-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190414_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcourse',
            name='user_golf_course',
        ),
    ]
